### ISSUE TITLE
Calculating Latency

### ISSUE THREAD

**Issue by Romiko** [spotahome/service-level-operator#15]
Hi,

How can I use the SLO operator to define a CRD for a simple SLO.

**SLO to serve 95% of requests within 300ms**

 sum(rate(http_request_duration_seconds_bucket{le="0.3"}[5m])) by (job)
/
  sum(rate(http_request_duration_seconds_count[5m])) by (job)

**Comment by primeroz** [comment]
Look at [this example](https://github.com/spotahome/service-level-operator/blob/master/test/manual/slos.yaml#L25) 

the SLO operator always need a `Total` and `Error` query so your rule will be slightly different, you will need to calculate the number of requests that were above your threshold , so `Total - Bucket{le="THRESHOLD}`

**Comment by Romiko** [comment]
Thanks for the reference example, much appreciated.

Also, do you require any assistance or further contributors to the project? As we are testing this out with a few of our dev teams that we engage with in an SRE capacity.
