### ISSUE TITLE
Configure Input backend in Operator instead of in CRD

### ISSUE THREAD

**Issue by marcantoine-bibeau** [spotahome/service-level-operator#8]
Hi, it would be very nice to be able to Configure Input backend in Operator instead of in CRD. IMO the the `address` in the CRD makes all the services defining their SLO having to know the prometheus (or any input) location.

Otherwise, awesome work! I really like that operator :)

**Comment by slok** [comment]
Hi @marcantoine-bibeau!

Yes you are right! it can be very repetitive, this is made so you can plug in different metrics from different sources for associated SLI/SLOs.

What do you think of loading a config file when starting the app with the default settings for the supported backends (Only prometheus at this moment) and use these settings when there are no settings on the CRD?

**Comment by marcantoine-bibeau** [comment]
That would be perfect. :)

**Comment by slok** [comment]
Hey @marcantoine-bibeau!

I just released a new version of the operator with the change that you requested.

`quay.io/spotahome/service-level-operator:v0.3.0`

Check [here](https://github.com/spotahome/service-level-operator#input-sli-sources) to know how you can enable this feature.

Best!

**Comment by marcantoine-bibeau** [comment]
Awesome! My plan is to start using that today or next week! I'll keep you posted! Thank you very much!

**Comment by marcantoine-bibeau** [comment]
Working perfectly :) Thanks again!
